### ISSUE TITLE
compatibility issues with Luma3DS

### ISSUE THREAD

**Issue by Ty-Dye** [derrekr/fastboot3DS#34] opened 2019-03-22 23:21 UTC
The commit (474eb30) on Luma3DS dose not boot on fastboot3DS but dose on B9S and GM9 (according to @AuroraWright).

I have a N3DS on system 11.9 as well as fastboot3ds 1.2 stable

Thanks for reading, I just wanted to inform the developers about compatibility issues 

UPDATE: This issue has been fixed on luma's end in this
https://github.com/AuroraWright/Luma3DS/commit/4e5f6e1eff1e8cff86565fa1abbea0a082365faf

**Comment by CrystaltheGlaceon** [comment] 2019-03-23 01:41
This was actually discovered by me this morning, but I was bit tired and didn’t feel like reporting it until I got some sleep. Moving on.
So it appears the latest commit doesn’t boot with fastboot. I tested this on both my old and new 3DS, both result in a softlock of just a black screen and blue LED. I can not replicate this issue when booting the build on B9S and GM9, tested again on an old and New 3DS

**Comment by Ty-Dye** [comment] 2019-03-23 02:20
@CrystaltheGlaceon yea, i just upgraded to fastboot today and I was planning todo so with luma as well (i was and am now on 9.1 official)

how could the devs (of fastboot or luma) fix this

**Comment by profi200** [comment] 2019-03-23 14:01
See https://github.com/AuroraWright/Luma3DS/issues/1232 for updates. I think this is a Luma bug.

**Comment by CrystaltheGlaceon** [comment] 2019-03-23 14:03
I think it might be both actually because Luma3DS still works just fine with GM9 and B9S, it's only on Fastboot that it has an issue. Something tells me that the lastest Luma commit does break the compatibility and it's up to either them or Fastboot to fix it.

**Comment by profi200** [comment] 2019-03-23 14:14
It appears the stack pointer is in a rather bad position which triggers the bug while it doesn't for other chainloaders. There are calls to functions messing with the stack before they are setting the stack pointer up correctly.

**Comment by CrystaltheGlaceon** [comment] 2019-03-23 14:57
Interesting, so which party should fix this?

**Comment by TuxSH** [comment] 2019-03-23 22:15
Fixed on my end, please check if there are other issues.

**Comment by Ty-Dye** [comment] 2019-03-23 22:23
@TuxSH Thank you very much! you do amazing work!

**Comment by CrystaltheGlaceon** [comment] 2019-03-23 22:25
@TuxSH
I will do some testing later tonight

**Comment by Ty-Dye** [comment] 2019-03-23 22:26
also im not sure if I should close this, ill leave it open for now just in case

**Comment by CrystaltheGlaceon** [comment] 2019-03-24 00:19
I can confirm that it now officially working again

**Comment by Ty-Dye** [comment] 2019-03-24 02:04
@CrystaltheGlaceon me to

**Closed** 2019-03-24 02:04 UTC
